// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"github.com/SpectatorNan/gorm-zero/gormc"

	"gorm.io/gorm"
)

type (
	caoModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Cao) error

		FindOne(ctx context.Context, id int64) (*Cao, error)
		Update(ctx context.Context, tx *gorm.DB, data *Cao) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultCaoModel struct {
		conn  *gorm.DB
		table string
	}

	Cao struct {
		Id int64        `gorm:"column:id"`
		C  sql.NullTime `gorm:"column:c"`
		D  sql.NullTime `gorm:"column:d"`
	}
)

func (Cao) TableName() string {
	return `"public"."cao"`
}

func newCaoModel(conn *gorm.DB) *defaultCaoModel {
	return &defaultCaoModel{
		conn:  conn,
		table: `"public"."cao"`,
	}
}

func (m *defaultCaoModel) Insert(ctx context.Context, tx *gorm.DB, data *Cao) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultCaoModel) FindOne(ctx context.Context, id int64) (*Cao, error) {
	var resp Cao
	err := m.conn.WithContext(ctx).Model(&Cao{}).Where("id = ?", id).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCaoModel) Update(ctx context.Context, tx *gorm.DB, data *Cao) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultCaoModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Delete(&Cao{}, id).Error

	return err
}

func (m *defaultCaoModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.conn.WithContext(ctx).Transaction(fn)
}
