// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type LoginResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Time string `json:"time"`
}

type BookReq struct {
	Name string `json:"name"`
}

type BookRepl struct {
	Id string `json:"id"`
}

type SonarWebhook struct {
	ServerURL     string      `json:"serverUrl"`
	TaskID        string      `json:"taskId"`
	Status        string      `json:"status"`
	AnalysedAt    string      `json:"analysedAt"`
	Revision      string      `json:"revision"`
	ProjectAAA    Project     `json:"projectAAA"`
	PropertiesAAA Properties  `json:"propertiesAAA"`
	QualityGates  QualityGate `json:"qualityGates"`
}

type Project struct {
	Key  string `json:"key"`
	Name string `json:"name"`
	URL  string `json:"url"`
}

type Properties struct {
}

type Condition struct {
	ErrorThreshold string `json:"errorThreshold"`
	Metric         string `json:"metric"`
	OnLeakPeriod   bool   `json:"onLeakPeriod"`
	Operator       string `json:"operator"`
	Status         string `json:"status"`
	Value          string `json:"value,omitempty"`
}

type QualityGate struct {
	Conditions []Condition `json:"conditions"`
	Name       string      `json:"name"`
	Status     string      `json:"status"`
}
